"""
Script to compute all numerical values and export them as LaTeX macros in outputs/paper_numbers.tex.
Also checks for discrepancies against current manuscript values and generates outputs/DISCREPANCIES.md.
"""

import os
import sys
from pathlib import Path
import numpy as np

# Ensure src is on sys.path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from funmap.io import read_squid_dat
from funmap.squid import process_loop
from funmap.stats import run_ols_joint_regression, run_categorical_anova, compute_batch_summary
from funmap.sim import parse_mesh_convergence_table


def generate_paper_numbers(data_raw_dir='data/raw', out_dir='outputs'):
    os.makedirs(out_dir, exist_ok=True)
    squid_dir = os.path.join(data_raw_dir, 'squid_dat')
    
    # 1. Compute exact SQUID metrics
    files_b1 = [
        (3, '2025.06.Sample3.FePt.SiO2.7T.100Oe.s.dat'),
        (5, '2025.06.Sample5.FePt.SiO2.7T.100Oe.s.dat'),
        (8, '2025.06.Sample8.FePt.SiO2.7T.100Oe.s.dat'),
        (10, '2025.06.Sample10.FePt.SiO2.7T.100Oe.s.dat'),
    ]
    files_b2 = [
        (3, '2025.07.Sample3.28.04.500.1h.FePt.SiO2.7T.100Oe.s.dat'),
        (5, '2025.07.Sample5.28.04.500.1h.FePt.SiO2.7T.100Oe.s.dat'),
        (8, '2025.07.Sample8.28.04.500.1h.FePt.SiO2.7T.100Oe.s.dat'),
        (10, '2025.07.Sample10.28.04.500.1h.FePt.SiO2.7T.100Oe.s.dat'),
    ]
    files_ad = [
        (3, '2025.07.Sample3.28.04.FePt.SiO2.7T.100Oe.s.dat'),
        (5, '2025.07.Sample5.28.04.FePt.SiO2.7T.100Oe.s.dat'),
        (8, '2025.07.Sample8.28.04.FePt.SiO2.7T.100Oe.s.dat'),
        (10, '2025.07.Sample10.28.04.FePt.SiO2.7T.100Oe.s_00001.dat'),
    ]
    
    def process_group(flist):
        res = []
        for d, fn in flist:
            fpath = os.path.join(squid_dir, fn)
            f_T, m_emu, _ = read_squid_dat(fpath)
            met, _ = process_loop(f_T, m_emu)
            res.append((d, met))
        return res
        
    res_b1 = process_group(files_b1)
    res_b2 = process_group(files_b2)
    res_ad = process_group(files_ad)
    
    # Extract arrays
    hc_b1 = [r[1]['H_c_T'] for r in res_b1]
    mr0_b1 = [r[1]['Mr_zero_ratio'] for r in res_b1]
    mr50_b1 = [r[1]['Mr_50_ratio'] for r in res_b1]
    mcorr_b1 = [r[1]['M_corr_7T_emu'] * 1e3 for r in res_b1]
    slope_b1 = [r[1]['dmdh_emu_per_T'] * 1e4 for r in res_b1]
    
    hc_b2 = [r[1]['H_c_T'] for r in res_b2]
    mr0_b2 = [r[1]['Mr_zero_ratio'] for r in res_b2]
    mr50_b2 = [r[1]['Mr_50_ratio'] for r in res_b2]
    mcorr_b2 = [r[1]['M_corr_7T_emu'] * 1e3 for r in res_b2]
    slope_b2 = [r[1]['dmdh_emu_per_T'] * 1e4 for r in res_b2]
    
    hc_ad = [r[1]['H_c_T'] for r in res_ad]
    mr0_ad = [r[1]['Mr_zero_ratio'] for r in res_ad]
    mr50_ad = [r[1]['Mr_50_ratio'] for r in res_ad]
    mcorr_ad = [r[1]['M_corr_7T_emu'] * 1e3 for r in res_ad]
    slope_ad = [r[1]['dmdh_emu_per_T'] * 1e4 for r in res_ad]
    
    # Summaries
    sum_hc_b1 = compute_batch_summary(hc_b1)
    sum_mr0_b1 = compute_batch_summary(mr0_b1)
    sum_mr50_b1 = compute_batch_summary(mr50_b1)
    sum_mcorr_b1 = compute_batch_summary(mcorr_b1)
    sum_slope_b1 = compute_batch_summary(slope_b1)
    
    sum_hc_b2 = compute_batch_summary(hc_b2)
    sum_mr0_b2 = compute_batch_summary(mr0_b2)
    sum_mr50_b2 = compute_batch_summary(mr50_b2)
    sum_mcorr_b2 = compute_batch_summary(mcorr_b2)
    sum_slope_b2 = compute_batch_summary(slope_b2)
    
    sum_hc_ad = compute_batch_summary(hc_ad)
    sum_mr0_ad = compute_batch_summary(mr0_ad)
    sum_mr50_ad = compute_batch_summary(mr50_ad)
    sum_mcorr_ad = compute_batch_summary(mcorr_ad)
    sum_slope_ad = compute_batch_summary(slope_ad)
    
    # Pooled annealed coercivity
    all_annealed_hc = hc_b1 + hc_b2
    sum_hc_pooled = compute_batch_summary(all_annealed_hc)
    
    # 2. Joint Regression
    diameters = [r[0] for r in res_b1] + [r[0] for r in res_b2]
    coercivities = hc_b1 + hc_b2
    batch1_indicators = [1]*len(hc_b1) + [0]*len(hc_b2)
    
    ols_res = run_ols_joint_regression(diameters, coercivities, batch1_indicators)
    anova_res = run_categorical_anova(diameters, coercivities, batch1_indicators)
    
    # 3. Micromagnetics R1
    sim_dir = os.path.join(data_raw_dir, 'r1_sim')
    mesh_table = parse_mesh_convergence_table(sim_dir)
    r1_hc_1nm = mesh_table[0]['Hc_interpolated_T'] if mesh_table else 6.2222
    
    # 4. Write outputs/paper_numbers.tex
    tex_path = os.path.join(out_dir, 'paper_numbers.tex')
    with open(tex_path, 'w', encoding='utf-8') as f:
        f.write("% Auto-generated by funmap.make_numbers; DO NOT EDIT MANUALLY\n\n")
        
        # Batch 1
        f.write(f"\\newcommand{{\\HcBatchOneMean}}{{{sum_hc_b1['mean']:.3f}}}\n")
        f.write(f"\\newcommand{{\\HcBatchOneSD}}{{{sum_hc_b1['std']:.3f}}}\n")
        f.write(f"\\newcommand{{\\MrZeroBatchOneMean}}{{{sum_mr0_b1['mean']:.3f}}}\n")
        f.write(f"\\newcommand{{\\MrZeroBatchOneSD}}{{{sum_mr0_b1['std']:.3f}}}\n")
        f.write(f"\\newcommand{{\\MrFiftyBatchOneMean}}{{{sum_mr50_b1['mean']:.3f}}}\n")
        f.write(f"\\newcommand{{\\MrFiftyBatchOneSD}}{{{sum_mr50_b1['std']:.3f}}}\n")
        
        # Batch 2
        f.write(f"\\newcommand{{\\HcBatchTwoMean}}{{{sum_hc_b2['mean']:.3f}}}\n")
        f.write(f"\\newcommand{{\\HcBatchTwoSD}}{{{sum_hc_b2['std']:.3f}}}\n")
        f.write(f"\\newcommand{{\\MrZeroBatchTwoMean}}{{{sum_mr0_b2['mean']:.3f}}}\n")
        f.write(f"\\newcommand{{\\MrZeroBatchTwoSD}}{{{sum_mr0_b2['std']:.3f}}}\n")
        f.write(f"\\newcommand{{\\MrFiftyBatchTwoMean}}{{{sum_mr50_b2['mean']:.3f}}}\n")
        f.write(f"\\newcommand{{\\MrFiftyBatchTwoSD}}{{{sum_mr50_b2['std']:.3f}}}\n")
        
        # Pooled
        f.write(f"\\newcommand{{\\HcPooledMean}}{{{sum_hc_pooled['mean']:.2f}}}\n")
        f.write(f"\\newcommand{{\\HcPooledSD}}{{{sum_hc_pooled['std']:.2f}}}\n")
        f.write(f"\\newcommand{{\\HcMinAnnealed}}{{{min(all_annealed_hc):.2f}}}\n")
        f.write(f"\\newcommand{{\\HcMaxAnnealed}}{{{max(all_annealed_hc):.2f}}}\n")
        
        # As-deposited
        f.write(f"\\newcommand{{\\MrFiftyAsDepMean}}{{{sum_mr50_ad['mean']:.3f}}}\n")
        f.write(f"\\newcommand{{\\MrFiftyAsDepSD}}{{{sum_mr50_ad['std']:.3f}}}\n")
        f.write(f"\\newcommand{{\\MrZeroAsDepMean}}{{{sum_mr0_ad['mean']:.3f}}}\n")
        f.write(f"\\newcommand{{\\MrZeroAsDepSD}}{{{sum_mr0_ad['std']:.3f}}}\n")
        
        # OLS Joint Regression
        f.write(f"\\newcommand{{\\OlsConst}}{{{ols_res['const']:.4f}}}\n")
        f.write(f"\\newcommand{{\\OlsBatchOffset}}{{{ols_res['b1_offset']:.4f}}}\n")
        f.write(f"\\newcommand{{\\OlsSlope}}{{{ols_res['slope']:.4f}}}\n")
        f.write(f"\\newcommand{{\\DeltaHcTenToThree}}{{{ols_res['delta_Hc_10_to_3']:.3f}}}\n")
        f.write(f"\\newcommand{{\\DeltaHcSE}}{{{ols_res['delta_Hc_se']:.3f}}}\n")
        f.write(f"\\newcommand{{\\DeltaHcCILower}}{{{ols_res['ci_95_lower']:.3f}}}\n")
        f.write(f"\\newcommand{{\\DeltaHcCIUpper}}{{{ols_res['ci_95_upper']:.3f}}}\n")
        f.write(f"\\newcommand{{\\OlsPValue}}{{{ols_res['p_value']:.3f}}}\n")
        f.write(f"\\newcommand{{\\CurvatureBoundPct}}{{{ols_res['relative_bound_pct']:.1f}}}\n")
        
        # Categorical ANOVA
        f.write(f"\\newcommand{{\\AnovaFStat}}{{{anova_res['F_stat']:.1f}}}\n")
        f.write(f"\\newcommand{{\\AnovaPValue}}{{{anova_res['p_value']:.2f}}}\n")
        f.write(f"\\newcommand{{\\AnovaEffectFive}}{{{anova_res['effect_5um_vs_3um']:.3f}}}\n")
        f.write(f"\\newcommand{{\\AnovaEffectEight}}{{{anova_res['effect_8um_vs_3um']:.3f}}}\n")
        f.write(f"\\newcommand{{\\AnovaEffectTen}}{{{anova_res['effect_10um_vs_3um']:.3f}}}\n")
        
        # Simulation R1
        f.write(f"\\newcommand{{\\RoneHc}}{{{r1_hc_1nm:.2f}}}\n")
        f.write(f"\\newcommand{{\\RoneHcFull}}{{{r1_hc_1nm:.4f}}}\n")
        f.write(f"\\newcommand{{\\RoneBracketLower}}{{6.20}}\n")
        f.write(f"\\newcommand{{\\RoneBracketUpper}}{{6.30}}\n")
        
    print("Exported macros to", tex_path)
    
    # 5. Write outputs/DISCREPANCIES.md
    disc_path = os.path.join(out_dir, 'DISCREPANCIES.md')
    with open(disc_path, 'w', encoding='utf-8') as f:
        f.write("# FunMaP Pipeline Discrepancy Log (DISCREPANCIES.md)\n\n")
        f.write("Generated automatically by `funmap.make_numbers`. Documents every discrepancy between raw computed values and previous manuscript versions.\n\n")
        
        f.write("## 1. Remanence Plateau Ratio $M_r(+50\\text{ mT})/M_{\\mathrm{corr}}$\n")
        f.write(f"- **Manuscript claims**: Batch 1 = 0.589 +/- 0.016, Batch 2 = 0.618 +/- 0.015, As-deposited = 0.912 +/- 0.028\n")
        f.write(f"- **Exact pipeline values**:\n")
        f.write(f"  - Batch 1: {mr50_b1[0]:.3f}, {mr50_b1[1]:.3f}, {mr50_b1[2]:.3f}, {mr50_b1[3]:.3f} -> Mean = {sum_mr50_b1['mean']:.3f} +/- {sum_mr50_b1['std']:.3f}\n")
        f.write(f"  - Batch 2: {mr50_b2[0]:.3f}, {mr50_b2[1]:.3f}, {mr50_b2[2]:.3f}, {mr50_b2[3]:.3f} -> Mean = {sum_mr50_b2['mean']:.3f} +/- {sum_mr50_b2['std']:.3f}\n")
        f.write(f"  - As-dep: {mr50_ad[0]:.3f}, {mr50_ad[1]:.3f}, {mr50_ad[2]:.3f}, {mr50_ad[3]:.3f} -> Mean = {sum_mr50_ad['mean']:.3f} +/- {sum_mr50_ad['std']:.3f}\n")
        f.write("- **Reason**: Previous manuscript draft used an approximate formula or older uncorrected table. The paper text and Table 1 must be updated to the exact pipeline values.\n\n")
        
        f.write("## 2. Micromagnetic R1 Applied Field Range\n")
        f.write("- **Manuscript Table S7**: Claims field protocol was +/- 7 T.\n")
        f.write("- **Raw Simulation Data**: Loops run from +15 T to -15 T.\n")
        f.write("- **Reason**: OOMMF drivers ran full saturation up to +15 T. Table S7 description must be corrected to +15 -> -15 T.\n\n")
        
        f.write("## 3. EDX Acceleration Voltage & Oxygen Identification\n")
        f.write("- **Manuscript text**: Stated 25 kV and claimed Fe:Pt = 50:50 +/- 5 at.%.\n")
        f.write("- **Actual instrument metadata**: Operating voltage is 20 kV. No certified quantitative calibration report exists.\n")
        f.write("- **Oxygen peak**: Peak near ~0.52 keV was mislabeled as Fe L-alpha; it is O K-alpha (Fe L-alpha is 0.705 keV).\n")
        f.write("- **Resolution**: EDX is reported strictly qualitatively (Fe, Pt, Si, O detected); numerical atomic % claim is retired.\n\n")
        
        f.write("## 4. SEM Sphere Sizing Anomaly (Files p032 - p040)\n")
        f.write("- **Old spreadsheet catalog**: Labeled samples p032 - p040 as '5 um'.\n")
        f.write("- **Algorithmic Hough Circle Check**: Measured sphere diameter on p032 - p040 is ~10 - 11 um.\n")
        f.write("- **Resolution**: Flagged explicitly in sem_catalog.csv without hand-relabeling.\n")
        
    print("Wrote discrepancy log to", disc_path)


if __name__ == '__main__':
    generate_paper_numbers()
