"""
Script to generate synthetic demo data for FunMaP.
All files are tagged with:
# SYNTHETIC DATA – not measured – generated by make_demo_data.py
Uses fixed random seed (42) for 100% deterministic reproducibility.
"""

import os
import sys
from pathlib import Path
import numpy as np

# Ensure src is on sys.path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))


def make_synthetic_squid_file(filepath, diameter_um, is_annealed, batch_idx, seed=42):
    """
    Generate a realistic MPMS3 .dat file format with synthetic hysteresis data.
    """
    rng = np.random.default_rng(seed)
    
    # Field schedule: +7 T down to -7 T and back to +7 T in Oe (1 T = 10,000 Oe)
    fields_down = np.linspace(70000, -70000, 141)
    fields_up = np.linspace(-70000, 70000, 141)
    fields = np.concatenate([fields_down, fields_up])
    
    # Background susceptibility: 1.33e-4 emu/T -> 1.33e-8 emu/Oe
    chi_bg = 1.33e-8
    
    # Magnetic parameters
    if is_annealed:
        # Hc ~ 1.05 - 1.18 T (10500 - 11800 Oe)
        hc_base = 11000 + (batch_idx * 500) + (10 - diameter_um) * 50
        hc = hc_base + rng.normal(0, 50)
        ms = 1.2e-3 * (1 + rng.normal(0, 0.05))
        mr_ratio = 0.62 + rng.normal(0, 0.01)
        
        # Branch moment modeling with tanh
        m_ferro_down = ms * np.tanh((fields_down + hc) / (0.4 * hc))
        m_ferro_up = ms * np.tanh((fields_up - hc) / (0.4 * hc))
        m_ferro = np.concatenate([m_ferro_down, m_ferro_up])
    else:
        # Soft A1 phase: Hc ~ 50 Oe
        hc = 50.0 + rng.normal(0, 5)
        ms = 0.85e-3 * (1 + rng.normal(0, 0.05))
        mr_ratio = 0.85
        m_ferro_down = ms * np.tanh((fields_down + hc) / 5000.0)
        m_ferro_up = ms * np.tanh((fields_up - hc) / 5000.0)
        m_ferro = np.concatenate([m_ferro_down, m_ferro_up])
        
    m_bg = chi_bg * fields
    noise = rng.normal(0, 1e-6, size=len(fields))
    m_total = m_ferro + m_bg + noise
    
    # Header lines
    header = [
        "; SYNTHETIC DATA – not measured – generated by make_demo_data.py",
        "[Header]",
        "FILE OPEN TIME, 06/20/2025 12:00:00 PM",
        "INFO, Synthetic MPMS3 SQUID VSM Data",
        f"SAMPLE_DIAMETER_UM, {diameter_um}",
        f"IS_ANNEALED, {is_annealed}",
        "[Data]",
        "Time,Magnetic Field (Oe),Moment (emu),Volts (V)"
    ]
    
    with open(filepath, 'w', encoding='utf-8') as f:
        for line in header:
            f.write(line + "\n")
        for i, (b, m) in enumerate(zip(fields, m_total)):
            t = i * 2.0
            v = m * 100.0
            f.write(f"{t:.2f},{b:.2f},{m:.8e},{v:.6f}\n")


def make_synthetic_xrd_file(filepath, sample_name, is_film=False, seed=42):
    """
    Generate synthetic Rigaku .xy file.
    """
    rng = np.random.default_rng(seed)
    two_theta = np.arange(20.0, 80.01, 0.02)
    
    # Baseline amorphous halo (SiO2) around 22 deg
    intensity = 500.0 + 2000.0 * np.exp(-((two_theta - 22.0) / 4.0) ** 2)
    
    # Si (220) peak at 47.30 deg
    intensity += 2.5e6 * np.exp(-((two_theta - 47.30) / 0.06) ** 2)
    # Cu K-beta satellite at 42.52 deg
    intensity += 3.5e4 * np.exp(-((two_theta - 42.52) / 0.06) ** 2)
    # W L-alpha at 45.18 deg
    intensity += 2.0e3 * np.exp(-((two_theta - 45.18) / 0.08) ** 2)
    
    if is_film or 'FePt' in sample_name:
        # FePt (111) peak at 41.06 deg
        intensity += 8.0e3 * np.exp(-((two_theta - 41.06) / 0.35) ** 2)
        
    intensity += rng.normal(0, 30.0, size=len(two_theta))
    intensity = np.maximum(intensity, 0.0)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write("# SYNTHETIC DATA – not measured – generated by make_demo_data.py\n")
        f.write(f"# Sample: {sample_name}\n")
        f.write("# Date: 2025-06-20\n")
        f.write("# 2Theta (deg)    Intensity (counts)\n")
        for tt, cnt in zip(two_theta, intensity):
            f.write(f"{tt:.3f}    {cnt:.1f}\n")


def make_synthetic_r1_csv(filepath, dx_nm, seed=42):
    """
    Generate synthetic R1 loop CSV matching raw format.
    Header: B_ext_T, Mx, My, Mz
    """
    fields = np.linspace(15.0, -15.0, 301)
    # Switching field around -6.22 T
    hc = -6.2223 - (dx_nm - 1.0) * 0.003
    
    mz = np.zeros_like(fields)
    for i, h in enumerate(fields):
        if h > hc:
            mz[i] = 0.7095 * (1.0 + 0.35 * (h / 15.0) if h >= 0 else 1.0 + 0.65 * (h / 6.22))
        else:
            mz[i] = -0.866 + 0.134 * ((h - hc) / (-15.0 - hc))
            
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write("# SYNTHETIC DATA – not measured – generated by make_demo_data.py\n")
        f.write("B_ext_T,Mx,My,Mz\n")
        for h, z in zip(fields, mz):
            f.write(f"{h:.4f},0.000000,0.000000,{z:.6f}\n")


def make_synthetic_r1_npz(filepath, b_val, mz_val, state_type, seed=42):
    """
    Generate synthetic slice NPZ matching raw R1 keys: m, norm, B, mz.
    Uses compact grid (32, 32, 16) for fast testing.
    """
    nx, ny, nz = 32, 32, 16
    m = np.zeros((nx, ny, nz, 3), dtype=np.float64)
    norm = np.zeros((nx, ny, nz, 1), dtype=np.float64)
    
    ms = 1.0e6 # A/m
    cx, cy = nx / 2.0, ny / 2.0
    
    for ix in range(nx):
        for iy in range(ny):
            for iz in range(nz):
                r = np.sqrt((ix - cx)**2 + (iy - cy)**2 + iz**2)
                if 8.0 <= r <= 15.0 and iz >= 0:
                    norm[ix, iy, iz, 0] = ms
                    # Radial normal
                    rx, ry, rz = (ix - cx)/r, (iy - cy)/r, iz/r
                    if state_type == 'remanence':
                        m[ix, iy, iz] = [rx * ms, ry * ms, rz * ms]
                    elif state_type == 'preswitch':
                        m[ix, iy, iz] = [rx * ms * 0.8, ry * ms * 0.8, (rz * 0.8 - 0.4) * ms]
                    else: # switched
                        m[ix, iy, iz] = [-rx * ms, -ry * ms, -rz * ms]
                        
    np.savez_compressed(
        filepath,
        m=m, norm=norm, B=np.array(b_val, dtype=np.float64), mz=np.array(mz_val, dtype=np.float64)
    )


def generate_all_demo_data(out_dir='demo_data'):
    """
    Generate complete synthetic demo data structure.
    """
    os.makedirs(out_dir, exist_ok=True)
    squid_dir = os.path.join(out_dir, 'squid_dat')
    xrd_dir = os.path.join(out_dir, 'xrd_xy')
    r1_dir = os.path.join(out_dir, 'r1_sim')
    sem_dir = os.path.join(out_dir, 'sem_tiff')
    
    for d in [squid_dir, xrd_dir, r1_dir, sem_dir]:
        os.makedirs(d, exist_ok=True)
        
    print(f"Generating synthetic demo data in '{out_dir}' (Seed 42)...")
    
    # 1. SQUID .dat files
    squid_files = [
        ('2025.06.Sample3.FePt.SiO2.7T.100Oe.s.dat', 3, True, 1),
        ('2025.06.Sample5.FePt.SiO2.7T.100Oe.s.dat', 5, True, 1),
        ('2025.06.Sample8.FePt.SiO2.7T.100Oe.s.dat', 8, True, 1),
        ('2025.06.Sample10.FePt.SiO2.7T.100Oe.s.dat', 10, True, 1),
        ('2025.07.Sample3.28.04.500.1h.FePt.SiO2.7T.100Oe.s.dat', 3, True, 2),
        ('2025.07.Sample5.28.04.500.1h.FePt.SiO2.7T.100Oe.s.dat', 5, True, 2),
        ('2025.07.Sample8.28.04.500.1h.FePt.SiO2.7T.100Oe.s.dat', 8, True, 2),
        ('2025.07.Sample10.28.04.500.1h.FePt.SiO2.7T.100Oe.s.dat', 10, True, 2),
        ('2025.07.Sample3.28.04.FePt.SiO2.7T.100Oe.s.dat', 3, False, 0),
        ('2025.07.Sample5.28.04.FePt.SiO2.7T.100Oe.s.dat', 5, False, 0),
        ('2025.07.Sample8.28.04.FePt.SiO2.7T.100Oe.s.dat', 8, False, 0),
        ('2025.07.Sample10.28.04.FePt.SiO2.7T.100Oe.s_00001.dat', 10, False, 0)
    ]
    for idx, (fname, dia, is_ann, b_idx) in enumerate(squid_files):
        p = os.path.join(squid_dir, fname)
        make_synthetic_squid_file(p, dia, is_ann, b_idx, seed=42 + idx)
        
    # 2. XRD files
    xrd_files = [
        ('GENBB-Nat_FePt_SiO_Film_20_80_2q_BB_s2p1dpm_2mmSL-20250509-132210.xy', 'Witness Film', True),
        ('GENBB-Nat_SiO2_3um_20_80_2q_BB_s2p1dpm_2mmSL-20250509-114400.xy', 'Bare 3um', False),
        ('GENBB-Nat_SiO2_5um_20_80_2q_BB_s2p1dpm_2mmSL-20250509-120000.xy', 'Bare 5um', False),
        ('GENBB-Nat_SiO2_8um_20_80_2q_BB_s2p1dpm_2mmSL-20250509-122000.xy', 'Bare 8um', False),
        ('GENBB-Nat_SiO2_10um_20_80_2q_BB_s2p1dpm_2mmSL-20250509-124000.xy', 'Bare 10um', False),
        ('GENBB-Nat_FePt_SiO2_3um_20_80_2q_BB_s2p1dpm_2mmSL-20250509-140000.xy', 'Annealed 3um', False),
        ('GENBB-Nat_FePt_SiO2_5um_20_80_2q_BB_s2p1dpm_2mmSL-20250509-142000.xy', 'Annealed 5um', False),
        ('GENBB-Nat_FePt_SiO2_8um_20_80_2q_BB_s2p1dpm_2mmSL-20250509-144000.xy', 'Annealed 8um', False),
        ('GENBB-Nat_FePt_SiO2_10um_20_80_2q_BB_s2p1dpm_2mmSL-20250509-150000.xy', 'Annealed 10um', False),
    ]
    for idx, (fname, sname, is_f) in enumerate(xrd_files):
        p = os.path.join(xrd_dir, fname)
        make_synthetic_xrd_file(p, sname, is_f, seed=100 + idx)
        
    # 3. R1 Simulation files matching raw filenames
    for dx in [1.0, 1.5, 2.0, 3.0, 4.0]:
        dx_str = f"{dx:.1f}".replace('.', 'p')
        p = os.path.join(r1_dir, f"R1_hemi_d200nm_cell_{dx_str}nm.csv")
        make_synthetic_r1_csv(p, dx, seed=200 + int(dx*10))
        
    npz_states = [
        ("r1_1nm_state_B+0.00T.npz", 0.0, 0.7095, 'remanence'),
        ("r1_1nm_state_B-6.20T.npz", -6.20, 0.247, 'preswitch'),
        ("r1_1nm_state_B-6.30T.npz", -6.30, -0.866, 'switched')
    ]
    for fname, b_val, mz_val, st_type in npz_states:
        p = os.path.join(r1_dir, fname)
        make_synthetic_r1_npz(p, b_val, mz_val, st_type, seed=300)
        
    print(f"Successfully generated all synthetic demo data in '{out_dir}'.")


if __name__ == '__main__':
    generate_all_demo_data()
